"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    from io import StringIO
    #import cStringIO.StringIO as BytesIO 
except ImportError:
    from io import BytesIO
import struct

class estado_gen(object):
    __slots__ = ["estado"]

    def __init__(self):
        self.estado = ""

    def encode(self):
        buf = BytesIO()
        buf.write(estado_gen._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        __estado_encoded = self.estado.encode('utf-8')
        buf.write(struct.pack('>I', len(__estado_encoded)+1))
        buf.write(__estado_encoded)
        buf.write(b"\0")

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != estado_gen._get_packed_fingerprint():
            raise ValueError("Decode error")
        return estado_gen._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = estado_gen()
        __estado_len = struct.unpack('>I', buf.read(4))[0]
        self.estado = buf.read(__estado_len)[:-1].decode('utf-8', 'replace')
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if estado_gen in parents: return 0
        tmphash = (0xf6803f59528633c8) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff)  + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if estado_gen._packed_fingerprint is None:
            estado_gen._packed_fingerprint = struct.pack(">Q", estado_gen._get_hash_recursive([]))
        return estado_gen._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

