"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    from cStringIO.StringIO import StringIO
except ImportError:
    from io import BytesIO
import struct

class habla_usuario_t(object):
    __slots__ = ["fraseusuario"]

    def __init__(self):
        self.fraseusuario = ""

    def encode(self):
        buf = BytesIO()
        buf.write(habla_usuario_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        __fraseusuario_encoded = self.fraseusuario.encode('utf-8')
        buf.write(struct.pack('>I', len(__fraseusuario_encoded)+1))
        buf.write(__fraseusuario_encoded)
        buf.write(b"\0")

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != habla_usuario_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return habla_usuario_t._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = habla_usuario_t()
        __fraseusuario_len = struct.unpack('>I', buf.read(4))[0]
        self.fraseusuario = buf.read(__fraseusuario_len)[:-1].decode('utf-8', 'replace')
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if habla_usuario_t in parents: return 0
        tmphash = (0x972f3b720d1cbfc3) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff)  + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if habla_usuario_t._packed_fingerprint is None:
            habla_usuario_t._packed_fingerprint = struct.pack(">Q", habla_usuario_t._get_hash_recursive([]))
        return habla_usuario_t._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

